-- MySQL Script generated by MySQL Workbench
-- Sat Jan 21 22:04:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coffee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffee` DEFAULT CHARACTER SET utf8 ;
USE `coffee` ;

-- -----------------------------------------------------
-- Table `coffee`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`orders` (
  `id` INT NOT NULL,
  `client_document` VARCHAR(11) NOT NULL,
  `description` VARCHAR(45) NULL,
  `delivery_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`user` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `document` VARCHAR(11) NOT NULL,
  `birthdate` DATE NULL,
  `phone` VARCHAR(11) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `image` VARCHAR(250) NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `coffee`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`address` (
  `id` VARCHAR(36) NOT NULL,
  `cep` VARCHAR(10) NULL,
  `number` VARCHAR(5) NULL,
  `street` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `city` VARCHAR(50) NULL,
  `state` VARCHAR(45) NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_address_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_address_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffee`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `coffee`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`product` (
  `id` INT NOT NULL,
  `image_product` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `category` VARCHAR(45) NULL,
  `price` DECIMAL(10) NULL,
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffee`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffee`.`user_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee`.`user_orders` (
  `id_product` INT NOT NULL,
  `id_orders` INT NOT NULL,
  `quantity_product` INT NULL,
  `price_product` VARCHAR(45) NULL,
  PRIMARY KEY (`id_product`, `id_orders`),
  INDEX `fk_category_has_product_product1_idx` (`id_orders` ASC) VISIBLE,
  INDEX `fk_category_has_product_category1_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_category_has_product_category1`
    FOREIGN KEY (`id_product`)
    REFERENCES `coffee`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_product_product1`
    FOREIGN KEY (`id_orders`)
    REFERENCES `coffee`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
